USE acore_playerbots;

DROP TABLE IF EXISTS `playerbots_dungeon_suggestion_abbrevation`;
CREATE TABLE `playerbots_dungeon_suggestion_abbrevation` (
    `id`           TINYINT(3)   NOT NULL AUTO_INCREMENT UNIQUE,
    `definition_slug` VARCHAR(255) NOT NULL,
    `abbrevation`  VARCHAR(16)  NOT NULL,

    PRIMARY KEY (`id`),
    KEY `definition_slug` (`definition_slug`)
)
ENGINE=MyISAM
DEFAULT CHARSET=utf8
ROW_FORMAT=FIXED
COMMENT='Playerbot dungeon suggestion abbrevations';

INSERT INTO `playerbots_dungeon_suggestion_abbrevation` VALUES

-- == Vanilla ==

(NULL, 'rfc'          , 'RFC'),
(NULL, 'rfc'          , 'RF'),
(NULL, 'dm'           , 'DM'),
(NULL, 'wc'           , 'WC'),
(NULL, 'sfk'          , 'SFK'),
(NULL, 'bfd'          , 'BFD'),
(NULL, 'stocks'       , 'Stockades'),
(NULL, 'stocks'       , 'Stockade'),
(NULL, 'stocks'       , 'Stocks'),
(NULL, 'gnomer'       , 'Gnomer'),
(NULL, 'sm-gy'        , 'SM: Graveyard'),
(NULL, 'sm-gy'        , 'SM Graveyard'),
(NULL, 'sm-gy'        , 'SM: GY'),
(NULL, 'sm-gy'        , 'SM GY'),
(NULL, 'sm-lib'       , 'SM: Library'),
(NULL, 'sm-lib'       , 'SM Library'),
(NULL, 'sm-lib'       , 'SM Lib'),
(NULL, 'rfk'          , 'RFK'),
(NULL, 'sm-armory'    , 'SM: Armory'),
(NULL, 'sm-armory'    , 'SM Armory'),
(NULL, 'sm-cath'      , 'SM: Cathedral'),
(NULL, 'sm-cath'      , 'SM Cath'),
(NULL, 'rfd'          , 'RFD'),
(NULL, 'ulda'         , 'Ulda'),
(NULL, 'mara-purple'  , 'Mara'),
(NULL, 'mara-orange'  , 'Mara'),
(NULL, 'mara-scepter' , 'Mara'),
(NULL, 'mara-princess', 'Mara'),
(NULL, 'zf'           , 'ZF'),
(NULL, 'st'           , 'Sunken Temple'),
(NULL, 'st'           , 'ST'),
(NULL, 'brd'          , 'BRD'),
(NULL, 'dm-w'         , 'DM: West'),
(NULL, 'dm-w'         , 'DM West'),
(NULL, 'dm-w'         , 'DM:W'),
(NULL, 'dm-w'         , 'DMW'),
(NULL, 'dm-e'         , 'DM: East'),
(NULL, 'dm-e'         , 'DM East'),
(NULL, 'dm-e'         , 'DM:E'),
(NULL, 'dm-e'         , 'DME'),
(NULL, 'dm-n'         , 'DM: North'),
(NULL, 'dm-n'         , 'DM North'),
(NULL, 'dm-n'         , 'DM:N'),
(NULL, 'dm-n'         , 'DMN'),
(NULL, 'lbrs'         , 'LBRS'),
(NULL, 'scholo'       , 'Scholo'),
(NULL, 'strat'        , 'Strat'),

-- == The Burning Crusade ==

(NULL, 'hfr' , 'Ramparts'),
(NULL, 'hfr' , 'Ramps'),
(NULL, 'hfr' , 'HFR'),
(NULL, 'bf'  , 'Blood Furnace'),
(NULL, 'bf'  , 'BF'),
(NULL, 'sp'  , 'Slave Pens'),
(NULL, 'sp'  , 'SP'),
(NULL, 'ub'  , 'Underbog'),
(NULL, 'ub'  , 'UB'),
(NULL, 'mt'  , 'Mana Tombs'),
(NULL, 'mt'  , 'MT'),
(NULL, 'ac'  , 'Crypts'),
(NULL, 'ac'  , 'AC'),
(NULL, 'seth', 'Sethekk'),
(NULL, 'seth', 'Seth'),
(NULL, 'oh'  , 'Old Hillsbrad'),
(NULL, 'oh'  , 'OH'),
(NULL, 'bm'  , 'BM'),
(NULL, 'mech', 'Mechanar'),
(NULL, 'mech', 'Mech'),
(NULL, 'bot' , 'Botanica'),
(NULL, 'bot' , 'Bot'),
(NULL, 'arc' , 'Arcatraz'),
(NULL, 'arc' , 'Arc'),
(NULL, 'sh'  , 'Shattered Halls'),
(NULL, 'sh'  , 'SH'),
(NULL, 'sv'  , 'Steamvaults'),
(NULL, 'sv'  , 'SV'),
(NULL, 'sl'  , 'Shadow Labyrinth'),
(NULL, 'sl'  , 'Shadow Labs'),
(NULL, 'sl'  , 'Slabs'),
(NULL, 'sl'  , 'SL'),
(NULL, 'mgt' , 'MGT'),
(NULL, 'mgt' , 'MT'),

-- == Wrath of the Lich King ==

(NULL, 'uk'    , 'UK'),
(NULL, 'nexus' , 'Nexus'),
(NULL, 'an'    , 'Azjol Nerub'),
(NULL, 'an'    , 'AN'),
(NULL, 'ak'    , 'Old Kingdom'),
(NULL, 'ak'    , 'AK'),
(NULL, 'ak'    , 'OK'),
(NULL, 'dtk'   , 'DTK'),
(NULL, 'vh'    , 'VH'),
(NULL, 'gd'    , 'GD'),
(NULL, 'hos'   , 'HoS'),
(NULL, 'hol'   , 'HoL'),
(NULL, 'cos'   , 'Old Strat'),
(NULL, 'cos'   , 'CoS'),
(NULL, 'oculus', 'Oculus'),
(NULL, 'oculus', 'OC'),
(NULL, 'up'    , 'UP'),
(NULL, 'toc'   , 'ToC'),
(NULL, 'fos'   , 'FoS'),
(NULL, 'pos'   , 'PoS'),
(NULL, 'hor'   , 'HoR');
